# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test3():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_3(self):
    self.driver.get("https://www.jd.com/")
    self.driver.set_window_size(1550, 878)
    self.driver.find_element(By.ID, "key").click()
    self.driver.find_element(By.ID, "key").send_keys("小米有线耳机")
    self.driver.find_element(By.CSS_SELECTOR, ".button").click()
    self.driver.find_element(By.CSS_SELECTOR, "#J_feature li:nth-child(1) i").click()
    element = self.driver.find_element(By.ID, "J_comment_100147417474")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.CSS_SELECTOR, "#warecard_100165361768 .skcolor_ljg:nth-child(2)").click()
    self.vars["win3947"] = self.wait_for_window(2000)
    self.driver.switch_to.window(self.vars["win3947"])
    self.driver.execute_script("window.scrollTo(0,37.599998474121094)")
    self.driver.find_element(By.ID, "InitCartUrl").click()
    element = self.driver.find_element(By.ID, "InitCartUrl")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    element = self.driver.find_element(By.LINK_TEXT, "Type-C白色")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.LINK_TEXT, "jd_oq70df203...")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.LINK_TEXT, "退出").click()
  
