package org.example;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class DateUtilTest {

    /**
     *
     * 等价类测试用例
     * */
    @Test
    public void Test01(){
        String year="2025";
        String month="4";
        String day="23";
        // 1
        String actual=DateUtil.nextDate(year,month,day);
        String expected="2025年4月24日";
        Assertions.assertEquals(actual,expected);
        // 2
        actual=DateUtil.nextDate("2024","2","29");
        expected="2024年3月1日";
        Assertions.assertEquals(actual,expected);
        // 3
        actual=DateUtil.nextDate("2024","5","31");
        expected="2024年6月1日";
        Assertions.assertEquals(actual,expected);
        //4
        actual=DateUtil.nextDate("2024","4","30");
        expected="2024年5月1日";
        Assertions.assertEquals(actual,expected);
        //5
        actual=DateUtil.nextDate("2051","1","1");
        expected="非法输入";
        Assertions.assertEquals(actual,expected);
        //6
        actual=DateUtil.nextDate("1888","1","1");
        expected="非法输入";
        Assertions.assertEquals(actual,expected);
        //7
        actual=DateUtil.nextDate("sda","1","1");
        expected="非法输入";
        Assertions.assertEquals(actual,expected);
        //8
        actual=DateUtil.nextDate("2000","0","1");
        expected="非法输入";
        Assertions.assertEquals(actual,expected);
        //9
        actual=DateUtil.nextDate("2024","13","1");
        expected="非法输入";
        Assertions.assertEquals(actual,expected);
        //10
        actual=DateUtil.nextDate("2000","asda","1");
        expected="非法输入";
        Assertions.assertEquals(actual,expected);
        //11
        actual=DateUtil.nextDate("2000","1","0");
        expected="非法输入";
        Assertions.assertEquals(actual,expected);
        //12
        actual=DateUtil.nextDate("2000","1","32");
        expected="非法输入";
        Assertions.assertEquals(actual,expected);
        //13
        actual=DateUtil.nextDate("2000","1","sda");
        expected="非法输入";
        Assertions.assertEquals(actual,expected);
        //14
        actual=DateUtil.nextDate("2024","2","30");
        expected="非法输入";
        Assertions.assertEquals(actual,expected);
        //15
        actual=DateUtil.nextDate("2025","2","29");
        expected="非法输入";
        Assertions.assertEquals(actual,expected);
        //16
        actual=DateUtil.nextDate("2024","5","32");
        expected="非法输入";
        Assertions.assertEquals(actual,expected);
        //17
        actual=DateUtil.nextDate("2024","4","31");
        expected="非法输入";
        Assertions.assertEquals(actual,expected);
        //18
        actual=DateUtil.nextDate("adsa","4","31");
        expected="非法输入";
        Assertions.assertEquals(actual,expected);

    }
    //边界值

    /**
     *
     * 用边界值
     */
    @Test
    public void test02(){
        String actual="";
        String expected="";
        //年份 的健壮性边界值分析
        //1
        actual=DateUtil.nextDate("1899","4","25");
        expected="非法输入";
        Assertions.assertEquals(actual,expected);
        //2
        actual=DateUtil.nextDate("1900","4","25");
        expected="1900年4月26日";
        Assertions.assertEquals(actual,expected);
        //3
        actual=DateUtil.nextDate("1901","4","25");
        expected="1901年4月26日";
        Assertions.assertEquals(actual,expected);
        //4
        actual=DateUtil.nextDate("2024","4","25");
        expected="2024年4月26日";
        Assertions.assertEquals(actual,expected);
        //5
        actual=DateUtil.nextDate("2049","4","25");
        expected="2049年4月26日";
        Assertions.assertEquals(actual,expected);
        //6
        actual=DateUtil.nextDate("2050","4","25");
        expected="2050年4月26日";
        Assertions.assertEquals(actual,expected);
        //7
        actual=DateUtil.nextDate("2051","4","25");
        expected="非法输入";
        Assertions.assertEquals(actual,expected);
        //8
        actual=DateUtil.nextDate("2024","0","15");
        expected="非法输入";
        Assertions.assertEquals(actual,expected);
        //9
        actual=DateUtil.nextDate("2024","1","15");
        expected="2024年1月16日";
        Assertions.assertEquals(actual,expected);
        //10
        actual=DateUtil.nextDate("2024","2","15");
        expected="2024年2月16日";
        Assertions.assertEquals(actual,expected);
        //11
        actual=DateUtil.nextDate("2024","6","15");
        expected="2024年6月16日";
        Assertions.assertEquals(actual,expected);
        //12
        actual=DateUtil.nextDate("2024","11","15");
        expected="2024年11月16日";
        Assertions.assertEquals(actual,expected);
        //13
        actual=DateUtil.nextDate("2024","12","15");
        expected="2024年12月16日";
        Assertions.assertEquals(actual,expected);
        //14
        actual=DateUtil.nextDate("2024","13","15");
        expected="非法输入";
        Assertions.assertEquals(actual,expected);
        //15
        actual=DateUtil.nextDate("2024","2","30");
        expected="非法输入";
        Assertions.assertEquals(actual,expected);
        //16
        actual=DateUtil.nextDate("2024","2","29");
        expected="2024年3月1日";
        Assertions.assertEquals(expected,actual);
        //17
        actual=DateUtil.nextDate("2024","2","1");
        expected="2024年2月2日";
        Assertions.assertEquals(expected,actual);
        //18
        actual=DateUtil.nextDate("2024","2","15");
        expected="2024年2月16日";
        Assertions.assertEquals(expected,actual);
        //19
        actual=DateUtil.nextDate("2024","2","2");
        expected="2024年2月3日";
        Assertions.assertEquals(expected,actual);
        //20
        actual=DateUtil.nextDate("2024","2","28");
        expected="2024年2月29日";
        Assertions.assertEquals(expected,actual);
        //21
        actual=DateUtil.nextDate("2024","2","0");
        expected="非法输入";
        Assertions.assertEquals(expected,actual);
        //22
        actual=DateUtil.nextDate("2024","1","0");
        expected="非法输入";
        Assertions.assertEquals(expected,actual);
        //23
        actual=DateUtil.nextDate("2024","1","1");
        expected="2024年1月2日";
        Assertions.assertEquals(expected,actual);
        //24
        actual=DateUtil.nextDate("2024","1","2");
        expected="2024年1月3日";
        Assertions.assertEquals(expected,actual);
        //25
        actual=DateUtil.nextDate("2024","1","15");
        expected="2024年1月16日";
        Assertions.assertEquals(expected,actual);
        //26
        actual=DateUtil.nextDate("2024","1","30");
        expected="2024年1月31日";
        Assertions.assertEquals(expected,actual);
        //27
        actual=DateUtil.nextDate("2024","1","31");
        expected="2024年2月1日";
        Assertions.assertEquals(expected,actual);
        //28
        actual=DateUtil.nextDate("2024","1","32");
        expected="非法输入";
        Assertions.assertEquals(expected,actual);
        //29
        actual=DateUtil.nextDate("2024","4","0");
        expected="非法输入";
        Assertions.assertEquals(expected,actual);
        //30
        actual=DateUtil.nextDate("2024","4","1");
        expected="2024年4月2日";
        Assertions.assertEquals(expected,actual);
        //31
        actual=DateUtil.nextDate("2024","4","2");
        expected="2024年4月3日";
        Assertions.assertEquals(expected,actual);
        //32
        actual=DateUtil.nextDate("2024","4","15");
        expected="2024年4月16日";
        Assertions.assertEquals(expected,actual);
        //33
        actual=DateUtil.nextDate("2024","4","29");
        expected="2024年4月30日";
        Assertions.assertEquals(expected,actual);
        //34
        actual=DateUtil.nextDate("2024","4","30");
        expected="2024年5月1日";
        Assertions.assertEquals(expected,actual);
        //35
        actual=DateUtil.nextDate("2024","4","31");
        expected="非法输入";
        Assertions.assertEquals(expected,actual);
        //36
        actual=DateUtil.nextDate("2025","2","0");
        expected="非法输入";
        Assertions.assertEquals(expected,actual);
        //37
        actual=DateUtil.nextDate("2025","2","1");
        expected="2025年2月2日";
        Assertions.assertEquals(expected,actual);
        //38
        actual=DateUtil.nextDate("2025","2","2");
        expected="2025年2月3日";
        Assertions.assertEquals(expected,actual);
        //39
        actual=DateUtil.nextDate("2025","2","15");
        expected="2025年2月16日";
        Assertions.assertEquals(expected,actual);
        //40
        actual=DateUtil.nextDate("2025","2","27");
        expected="2025年2月28日";
        Assertions.assertEquals(expected,actual);
        //41
        actual=DateUtil.nextDate("2025","2","28");
        expected="2025年3月1日";
        Assertions.assertEquals(expected,actual);
        //42
        actual=DateUtil.nextDate("2025","2","29");
        expected="非法输入";
        Assertions.assertEquals(expected,actual);

    }
    /**
     *
     * 判定表
     */
    @Test
    public void test03(){
        String actual="";
        String expected="";
        //1
        actual=DateUtil.nextDate("2024","4","27");
        expected="2024年4月28日";
        Assertions.assertEquals(expected,actual);
        //2
        actual=DateUtil.nextDate("2024","4","28");
        expected="2024年4月29日";
        Assertions.assertEquals(expected,actual);
        //3
        actual=DateUtil.nextDate("2024","4","29");
        expected="2024年4月30日";
        Assertions.assertEquals(expected,actual);
        //4
        actual=DateUtil.nextDate("2024","4","30");
        expected="2024年5月1日";
        Assertions.assertEquals(expected,actual);
        //5
        actual=DateUtil.nextDate("2024","4","31");
        expected="非法输入";
        Assertions.assertEquals(expected,actual);

        //6
        actual=DateUtil.nextDate("2024","1","27");
        expected="2024年1月28日";
        Assertions.assertEquals(expected,actual);
        //7
        actual=DateUtil.nextDate("2024","1","28");
        expected="2024年1月29日";
        Assertions.assertEquals(expected,actual);
        //8
        actual=DateUtil.nextDate("2024","1","29");
        expected="2024年1月30日";
        Assertions.assertEquals(expected,actual);
        //9
        actual=DateUtil.nextDate("2024","1","30");
        expected="2024年1月31日";
        Assertions.assertEquals(expected,actual);
        //10
        actual=DateUtil.nextDate("2024","1","31");
        expected="2024年2月1日";
        Assertions.assertEquals(expected,actual);
        //11
        actual=DateUtil.nextDate("2024","12","27");
        expected="2024年12月28日";
        Assertions.assertEquals(expected,actual);
        //12
        actual=DateUtil.nextDate("2024","12","28");
        expected="2024年12月29日";
        Assertions.assertEquals(expected,actual);
        //13
        actual=DateUtil.nextDate("2024","12","29");
        expected="2024年12月30日";
        Assertions.assertEquals(expected,actual);
        //14
        actual=DateUtil.nextDate("2024","12","30");
        expected="2024年12月31日";
        Assertions.assertEquals(expected,actual);
        //15
        actual=DateUtil.nextDate("2024","12","31");
        expected="2025年1月1日";
        Assertions.assertEquals(expected,actual);

        //16
        actual=DateUtil.nextDate("2024","2","27");
        expected="2024年2月28日";
        Assertions.assertEquals(expected,actual);
        //16
        actual=DateUtil.nextDate("2024","2","28");
        expected="2024年2月29日";
        Assertions.assertEquals(expected,actual);
        //16
        actual=DateUtil.nextDate("2024","2","29");
        expected="2024年3月1日";
        Assertions.assertEquals(expected,actual);
        //16
        actual=DateUtil.nextDate("2024","2","30");
        expected="非法输入";
        Assertions.assertEquals(expected,actual);
        //16
        actual=DateUtil.nextDate("2024","2","31");
        expected="非法输入";
        Assertions.assertEquals(expected,actual);
        //16
        actual=DateUtil.nextDate("2025","2","27");
        expected="2025年2月28日";
        Assertions.assertEquals(expected,actual);
        //16
        actual=DateUtil.nextDate("2025","2","28");
        expected="2025年3月1日";
        Assertions.assertEquals(expected,actual);
        //16
        actual=DateUtil.nextDate("2025","2","29");
        expected="非法输入";
        Assertions.assertEquals(expected,actual);
        //16
        actual=DateUtil.nextDate("2025","2","30");
        expected="非法输入";
        Assertions.assertEquals(expected,actual);
        //16
        actual=DateUtil.nextDate("2025","2","31");
        expected="非法输入";
        Assertions.assertEquals(expected,actual);




    }
}